#!/bin/sh
#########
alias tmt='tmux attach || tmux new-session'
alias tma='tmux new-session -A -s '
alias tmn='tmux new-session'
alias tml='tmux ls'


alias bz='bazel'
alias g='git'
alias cdc='cd ~/Code'
alias manapool='cd ~/Code/manapool'
alias python=python3
alias rerc=". ~/.bashrc"
alias vim="nvim"
alias rpc="grpc_cli"
alias bz="bazel"
alias bzb="bazel build "
alias bzq="bazel query "
alias bzqb="bazel query --output=build "
alias grh="gristory"

# Gcloud
alias gcp="gcloud"
alias gcpswitch="gcloud config configurations activate "


alias dockerex='docker rm $(docker ps -a -q -f status=exited)'

function catless() {
    cat "$1" | less
}
function gristory() {
    history | grep "$1" | less
}
function pless() {
    $@ 2>&1 | less
}

function join_by {
  local d=${1-} f=${2-}
  if shift 2; then
    printf %s "$f" "${@/#/$d}"
  fi
}

function psgrep {
  ps -ef  | head -1; ps -ef  | grep -v grep | grep "$1"
}

function getport {
  sudo lsof -n -i ":$1" | head -1; sudo lsof -n -i ":$1" | grep LISTEN
}

# Makes bash completion for alias'd commands.
if [[ -r $HOME/.bash_completion ]]; then
    . $HOME/.bash_completion
fi


# GCP Stuff
function gcp_info() {
  PROJECT_NUMBER="$(gcloud projects list --filter="$(gcloud config get-value project)"  --format="value(PROJECT_NUMBER)")"
  PROJECT_ID="$(gcloud config get-value project)"
  printf %s "" "$PROJECT_ID" " " "$PROJECT_NUMBER"
}
# Auth to GCP using the provided config name.
function gcpauth() {
  if [[ -n "$1" ]]; then
    config_name="$1"
    gcloud config configurations activate "$config_name"
  fi
  gcloud auth login --update-adc
  gcloud auth application-default set-quota-project "$(gcloud config get project)"
}
alias cdupsell="cd $HOME/Code/mahon/upsell/"

