#!/bin/sh
#########
alias tmt='tmux attach || tmux new-session'
alias tma='tmux new-session -A -s '
alias tmn='tmux new-session'
alias tml='tmux ls'


alias bz='bazel'
alias g='git'
alias cdc='cd ~/Code'
alias manapool='cd ~/Code/manapool'
alias python=python3
alias rerc=". ~/.bashrc"
alias vim="nvim"
alias rpc="grpc_cli"
alias bz="bazel"
alias bzb="bazel build "
alias bzq="bazel query "
alias grh="gristory"


alias dockerex='docker rm $(docker ps -a -q -f status=exited)'

function catless() {
    cat "$1" | less
}
function gristory() {
    history | grep "$1" | less
}
function pless() {
    $@ 2>&1 | less
}

# Makes bash completion for alias'd commands.
if [[ -r $HOME/.bash_completion ]]; then
    . $HOME/.bash_completion
fi

