#!/bin/sh
#########

export HISTFILESIZE=1000000
export PROMPT_COMMAND='history -a'
# export JAVA_HOME="$(dirname $(dirname $(realpath $(which javac))))"
export VIRTUAL_ENV_DISABLE_PROMPT=1

if [[ -f "$HOME/.bash_utils" ]]; then
    . "$HOME/.bash_utils"
fi
# Rust
if [[ -f "$HOME/.cargo/env" ]]; then
    . "$HOME/.cargo/env"
fi
if [[ -f "/etc/bazel-complete.bash" ]]; then
    . /etc/bazel-complete.bash
fi

# Go
export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:$HOME/go/bin/

defvenv="default"
if [[ -f "$HOME/Code/python/venvs/${defvenv}/bin/activate" ]]; then
    . "$HOME/Code/python/venvs/${defvenv}/bin/activate"
fi

export RT="$HOME/Code/rust/rustdocker"
export PATH="$PATH:$HOME/.local/bin/"


if [[ -f "$HOME/.bash_theme" ]]; then
   . "$HOME/.bash_theme"
fi

# Make sure to install nvm.
export NODE_PATH=/usr/lib/node_modules
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Install angular, then uncomment this line.
# source <(ng completion script)
export WINEPREFIX=~/prefix32
export WINEARCH=win32

export PATH=$PATH:~/bin/
if [[ -f /usr/bin/terraform ]]; then
   complete -C /usr/bin/terraform terraform
fi

# WSL Stuff
# export BROWSER=wslview
alias BROWSER="/mnt/Program Files/Google/Chrome/Application/chrome.exe"


# postgres
PATH=$PATH:/usr/lib/postgresql/14/bin
export PATH
